sudo: required
services:
  - docker  

before_install:
  - docker build -f Dockerfile.dev -t aliamyn/docker-react .

script:
  - docker run -e CI=true aliamyn/docker-react npm run test -- --coverage 

deploy:
  provider: elasticbeanstalk
  #region depande on url aws provide as after creation docker env with elastic beinTalk
  region: "us-west-2"
  app: "docker"
  env: "docker-env"
  # to get the back name go to search S3 and then and search for name start eith the same region
  bucket_name: "elasticbeanstalk-us-west-2-26686493"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

