sudo: required
services:
  - docker  

before_install:
  - docker build -f Dockerfile.dev -t aliamyn/docker-react .

script:
  - docker run -e CI=true aliamyn/docker-react npm run test -- --coverage  